apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  namespace: jmeter
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: NodePort
