apiVersion: v1
kind: Service
metadata:
  name: reporter
  namespace: jmeter
  labels:
    app: reporter
spec:
  ports:
    - port: 8686
      targetPort: 8686
  selector:
    app: reporter
  type: NodePort
