apiVersion: v1
kind: Service
metadata:
  namespace: jmeter
  name: slave
spec:
  ports:
    - name: rmi-localport
      port: 50000
    - name: server-port
      port: 1099
  selector:
    app: jmeter-slave
