apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: services

bases:
- ../deployments

resources:
- jmeter-master-service.yaml
- jmeter-slave-service.yaml
- jmeter-grafana-service.yaml
- jmeter-grafana-reporter-service.yaml
- jmeter-influxdb-service.yaml
