apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
  namespace: jmeter
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: create-credentials
        image: grafana/grafana:5.2.0
        command:
          - /bin/bash
          - "-c"
          - |
            curl 'http://admin:admin@127.0.0.1:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"name":"jmeterdb","type":"influxdb","url":"http://jmeter-influxdb:8086","access":"proxy","isDefault":true,"database":"jmeter","user":"admin","password":"admin"}'
