apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
  namespace: jmeter
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: create-credentials
        image: influxdb:1.8
        command:
          - /bin/bash
          - "-c"
          - |
            cp -r /load_test /jmeter/load_test
            chmod 755 /jmeter/load_test
