apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: jmeter
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    domain: sit.coffee-concepts.com
    root_url: https://sit.coffee-concepts.com/grafana
    serve_from_sub_path: true
