apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: jmeter
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    domain: example.com
    root_url: https://example.com/grafana
    serve_from_sub_path: true
