apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: jmeter
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    domain: localhost:3000
    root_url: http://localhost:3000/grafana
    serve_from_sub_path: true
