apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
        # env: fargate
    spec:
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'mkdir -p /jmeter']
      containers:
      - name: master
        image: kentpun/jmeter-distributed:jmeter-master
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 60000
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "0.5"
            memory: 4Gi
        volumeMounts:
        - name: loadtest
          mountPath: /load_test
          subPath: "load_test"
      volumes:
      - name: loadtest
        configMap:
          name: jmeter-load-test
