apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  namespace: jmeter
  labels:
    app: jmeter-master
data:
  load_test: |
    #!/bin/bash
    #Script created to invoke jmeter test script with the slave POD IP addresses
    #Script should be run like: ./load_test "path to the test script in jmx format"
    jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 slave | cut -d' ' -f1 | paste -d, -s | sed -e 's/ /,/g'`
