apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: jmeter
  labels:
    app: influxdb
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [admin]
      enabled = true

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003"
    database = "jmeter"
