apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: deployments

bases:
- ../namespace

resources:
- jmeter-master-configmap.yaml
- jmeter-master.yaml
- jmeter-slave.yaml
- jmeter-grafana.yaml
- jmeter-grafana-reporter.yaml
- jmeter-influxdb.yaml
- jmeter-influxdb-configmap.yaml
